[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements_minimal.txt"

[deploy]
startCommand = "uvicorn main_minimal:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"